# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.service.enabled", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151014143721");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1452537328");
user_pref("browser.slowStartup.averageTime", 6665);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20151014143721");
user_pref("browser.startup.homepage_override.mstone", "41.0.2");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1448910909241");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1448824604623");
user_pref("datareporting.policy.firstRunTime", "1448824509240");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4233);
user_pref("datareporting.sessions.current.main", 187);
user_pref("datareporting.sessions.current.sessionRestored", 4793);
user_pref("datareporting.sessions.current.startTime", "1452537323373");
user_pref("datareporting.sessions.current.totalTime", 66);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1448824503635,\"a\":4,\"t\":36,\"c\":true,\"m\":145,\"fp\":1718,\"sr\":11208}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1448824590395,\"a\":11,\"t\":55,\"c\":true,\"m\":204,\"fp\":3800,\"sr\":4224}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "41.0.2");
user_pref("extensions.lastPlatformVersion", "41.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\PROGRA~1\\\\MOZILL~1\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"41.0.2\",\"st\":1444936959388,\"mt\":1444936958267}}}");
user_pref("gecko.buildID", "20151014143721");
user_pref("gecko.mstone", "41.0.2");
user_pref("gfx.blacklist.direct2d", 4);
user_pref("gfx.blacklist.layers.direct3d9", 4);
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("gfx.driver-init.appVersion", "41.0.2");
user_pref("gfx.driver-init.deviceID", "0x9802");
user_pref("gfx.driver-init.driverVersion", "8.862.0.0");
user_pref("gfx.driver-init.feature-d2d", false);
user_pref("gfx.driver-init.feature-d3d11", true);
user_pref("gfx.driver-init.status", 2);
user_pref("media.gmp-eme-adobe.enabled", false);
user_pref("media.gmp-gmpopenh264.enabled", false);
user_pref("media.gmp-manager.buildID", "20151014143721");
user_pref("media.gmp-manager.lastCheck", 1452537389);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 0);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 43010);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugin.state.java", 0);
user_pref("plugin.state.npctrl", 0);
user_pref("plugin.state.npdeployjava", 0);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x9802");
user_pref("sanity-test.driver-version", "8.862.0.0");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "41.0.2");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1452537323);
user_pref("toolkit.telemetry.cachedClientID", "30f08106-75e8-487b-8bd1-8ac30af0950e");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
